# Tink (via androidx.security:security-crypto) references compile-time-only
# errorprone annotations that are not on the runtime classpath.
# Rules generated by AGP in build/app/outputs/mapping/release/missing_rules.txt.
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.CheckReturnValue
-dontwarn com.google.errorprone.annotations.Immutable
-dontwarn com.google.errorprone.annotations.RestrictedApi
